version: 2

jobs:
  node:
    docker:
      - image: circleci/node:11.9.0
    steps:
      - checkout
      - run: sudo npm install -g npm@6.5.0
      - restore_cache: 
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache: 
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: npm run test
  node_latest:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: sudo npm install -g npm@latest
      - restore_cache: 
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache: 
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: npm run test

workflows:
  Mireks tests:
    jobs:
      - node
      - node_latest
  version: 2
      