export default {
	bgColor: ' #0c1a3f',
	bgLightColor: ' #182649',
	mutedWhite: ' #8c8e93',
	orange: ' #ff4501',
	vibrantBlue: ' #0ec7ff',
	mutedBlue: ' #0f96c2',
	globalPaddingVertical: ' calc(5vh + 4rem)',
	globalPaddingHorizontal: ' calc(12vw + 1rem)',
	roundBorderColor: ' rgba(49, 78, 150, 0.3)',
	roundBgRadius: ' calc(1vmin + 1rem)',
	roundBgColor: ' #151b2b',
	servicesHeight: ' calc(100vh - calc(5vh + 4rem) * 2)',
	servicesWidth: ' calc(63vw)',
	contactWidth: ' calc(20rem + 5vw)',
	contactHorizontalPadding: ' 2vw',
	contactRightMargin: ' calc(0.5rem + 1vw)',
	contactFontSize: ' 1.5rem',
	contactSpaceConst: ' calc((2vw * 2 + 1.5rem))',
	contactSpace: ' calc((calc((2vw * 2 + 1.5rem))) * var(--index))',
	contactWholeWidth: ' calc(calc(20rem + 5vw) + calc((2vw * 2 + 1.5rem)) * (var(--length) - 1))',
	contactMove: ' calc((calc(20rem + 5vw) - calc((2vw * 2 + 1.5rem))) * -1)',
	contactMiddle: ' calc((calc((calc((2vw * 2 + 1.5rem))) * var(--index)) * -1) + (calc(calc(20rem + 5vw) + calc((2vw * 2 + 1.5rem)) * (var(--length) - 1)) / 2) -(calc(20rem + 5vw) / 2))',
	contactHeight: ' 6rem',
	mqPhoneBreakPx: ' 600px',
	mqPhoneBreak: ' "(max-width: 600px)"',
	mqPhone: '"screen and (max-width: 600px;"',
	mqTabletBreakPx: ' 900px',
	mqTabletBreak: ' "(max-width: 900px)"',
	mqTablet: '"screen and (max-width: 900px;"',
	mqTabletNotPhone: '"screen and (min-width: 600px) and (max-width: 900px;"',
	globalPaddingTopOverrideMaxPx: ' 600px',
	globalPaddingTopOverrideAmount: ' 3rem',
};